# Generated by Django 4.2.25 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signyu_certificate_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='document',
            name='signyu_download_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
