# Generated by Django 4.2.25 on 2026-09-28 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_document_signyu_certificate_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key_prefix', models.CharField(editable=False, max_length=16)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
                ('webhook_secret', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='OutboundWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('payload', models.JSONField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='documents.apiclient')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_webhooks', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='api_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.apiclient'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('api_client', 'external_ref')},
        ),
    ]
